<?php

require_once '../php/Connection.php';

$codigba = filter_input(INPUT_GET, 'codigba');

if ($codigba === '') {
    
} else {
    $query = mysqli_query(Connection::getInstance()->conectar(), "SELECT *, inventario.clasificacion AS 'inventario.clasificacion' "
            . "FROM librarydb.inventario "
            . "INNER JOIN titulos ON inventario.num_titulo = titulos.num_titulo "
            . "INNER JOIN autor_titulo ON inventario.num_titulo = autor_titulo.num_titulo "
            . "INNER JOIN autores ON autor_titulo.num_autor = autores.num_autor "
            . "INNER JOIN bibliotecas ON inventario.num_biblioteca = bibliotecas.num_biblioteca "
            . "INNER JOIN materiales ON inventario.num_material = materiales.num_material "
            . "WHERE inventario.num_inventario = '" . $codigba . "';");
    echo '<hr><h2 class="text-center">Modificando datos del libro ' . $codigba  .' </h2>';
    if (mysqli_num_rows($query) != o) {
        while ($row = mysqli_fetch_array($query)) {
           echo '<hr><hr>';
                       echo '<div class="form-horizontal">';
                           echo '<div id="caja" class="form-group">';
                               echo '<div id="020" class="input-group input-group-sm col-lg-10">';
                                   echo '<div class="input-group">';
                                       echo '<span class="input-group-addon" style="background-color:#80d4ff"><strong>ISBN 020</strong></span>';
                                       echo '<span class="input-group-btn">';
                                           echo '<button disabled="" data-toggle="tooltip" title="Número Internacional Normalizado para Libros" class="btn btn-basic" type="button">$a</button>';
                                       echo '</span>';
                                       echo '<input id="isbn" name="isbn" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button id="btn-isbn" class="btn btn-danger" type="button"><i class="glyphicon glyphicon-trash"></i></button>'; 
                                       echo '</span>';
                                   echo '</div>';                                        
                               echo '</div>';
                               echo '<div id="041" class=" input-group input-group-sm col-lg-10">';
                                   echo '<div class="input-group">';
                                       echo '<span class="input-group-addon" style="background-color:#80d4ff"><strong>Idioma 041</strong></span>';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Código de idioma del texto-pista de sonido o título separado" class="btn btn-warning" type="button">$a</button>';
                                       echo '</span>';
                                       echo '<input id="idioma" name="idioma" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Código de idiomay/o traducciones intermedias del texto original" class="btn btn-basic" type="button">$h</button>';
                                       echo '</span>';
                                       echo '<input name="b" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Código del idioma del sumario o resumen/título o subtítulo sobreimpreso" class="btn btn-basic" type="button">$b</button>';
                                       echo '</span>';
                                       echo '<input name="c" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Código de idioma cantado o hablado" class="btn btn-basic" type="button">$d</button>';
                                       echo '</span>';
                                       echo '<input name="h" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Código del idioma de la tabla de contenido" class="btn btn-basic" type="button">$f</button>';
                                       echo '</span>';
                                       echo '<input name="n" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Código del idioma acompañado de otro tipo de material que no sea libreto" class="btn btn-basic" type="button">$g</button>';
                                       echo '</span>';
                                       echo '<input name="p" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Código del idioma de subtítulos" class="btn btn-basic" type="button">$j</button>';
                                       echo '</span>';
                                       echo '<input name="p" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button id="btn-idioma" class="btn btn-danger" type="button"><i class="glyphicon glyphicon-trash"></i></button>'; 
                                       echo '</span>';
                                   echo '</div>';
                               echo '</div>';
                               echo '<div id="082" class="input-group input-group-sm col-lg-10">';
                                   echo '<div class="input-group">';
                                       echo '<span class="input-group-addon" style="background-color: #80d4ff"><strong>Dewey 082</strong></span>';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toggle="tooltip" title="Número de clasificación decimal de Dewey" class="btn btn-basic" type="button">$a</button>';
                                       echo '</span>';
                                       echo '<input name="clasificacion" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toggle="tooltip" title="Cutter" class="btn btn-basic" type="button">$b</button>';
                                       echo '</span>';
                                       echo '<input name="cutter" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button class="btn btn-basic" type="button">$2</button>';
                                       echo '</span>';
                                       echo '<input name="cutter2" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button id="btn-dewey" class="btn btn-danger" type="button"><i class="glyphicon glyphicon-trash"></i></button>'; 
                                       echo '</span>';
                                   echo '</div>';
                               echo '</div>';
                               echo '<div id="094" class="input-group input-group-sm col-lg-10">';
                                   echo '<div class="input-group">';
                                       echo '<span class="input-group-addon" style="background-color: #80d4ff"><strong>Tesis 094</strong></span>';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toggle="tooltip" title="Número de clasificación de Tesis" class="btn btn-basic" type="button">$a</button>';
                                       echo '</span>';
                                       echo '<input tesis name="tesis" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button class="btn btn-basic" type="button">$b</button>';
                                       echo '</span>';
                                       echo '<input name="b_tesis" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button class="btn btn-basic" type="button">$2</button>';
                                       echo '</span>';
                                       echo '<input name="2_tesis" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button id="btn-tesis" class="btn btn-danger" type="button"><i class="glyphicon glyphicon-trash"></i></button>'; 
                                       echo '</span>';
                                   echo '</div>';
                               echo '</div>';
                               echo '<div id="099" class="input-group input-group-sm col-lg-10">';
                                   echo '<div class="input-group">';
                                       echo '<span class="input-group-addon" style="background-color: #80d4ff"><strong>Clasificación 099</strong></span>';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toggle="tooltip" title="Número de clasificación de la Biblioteca" class="btn btn-basic" type="button">$a</button>';
                                       echo '</span>';
                                       echo '<input name="clasificacion" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button class="btn btn-basic" type="button">$b</button>';
                                       echo '</span>';
                                       echo '<input name="clasific_b" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button class="btn btn-basic" type="button">$2</button>';
                                       echo '</span>';
                                       echo '<input name="clasific_2" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button id="btn-clasific" class="btn btn-danger" type="button"><i class="glyphicon glyphicon-trash"></i></button>'; 
                                       echo '</span>';
                                   echo '</div>';
                               echo '</div>';
                               echo '<div id="100" class="input-group input-group-sm col-lg-10">';
                                   echo '<div class="input-group">';
                                       echo '<span class="input-group-addon" style="background-color:#80d4ff"><strong>Autor 100</strong></span>';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toggle="tooltip" title="Nombre" class="btn btn-default btn-warning" type="button">$a</button>';
                                       echo '</span>';
                                       echo '<input id="nombre_autor" name="autor" type="text" class="form-control" value="">'; 
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toggle="tooltip" title="Fechas" class="btn btn-default btn-success" type="button">$d</button>';
                                       echo '</span>';
                                       echo '<input name="fechas" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toggle="tooltip" title="Relación" class="btn btn-default btn-warning" type="button">$e</button>';
                                       echo '</span>';
                                       echo '<input name="relacion" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button id="btn-autor" class="btn btn-danger" type="button"><i class="glyphicon glyphicon-trash"></i></button>'; 
                                       echo '</span>';
                                   echo '</div>';
                               echo '</div>';
                               echo '<div id="245" class="input-group input-group-sm col-lg-10">';
                                   echo '<div class="input-group">';
                                       echo '<span class="input-group-addon" style="background-color:#80d4ff"><strong>Título 245</strong></span>';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Tí-tulo" class="btn btn-basic" type="button">$a</button>';
                                       echo '</span>';
                                       echo '<input name="titulo" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Resto del tí-tulo" class="btn btn-basic" type="button">$b</button>';
                                       echo '</span>';
                                       echo '<input name="b" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Mención de responsabiblidad, etc." class="btn btn-basic" type="button">$c</button>';
                                       echo '</span>';
                                       echo '<input name="c" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Medio" class="btn btn-basic" type="button">$h</button>';
                                       echo '</span>';
                                       echo '<input name="h" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Número de parte/sección de la obra" class="btn btn-basic" type="button">$n</button>';
                                       echo '</span>';
                                       echo '<input name="n" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Número de parte/sección de la obra" class="btn btn-basic" type="button">$p</button>';
                                       echo '</span>';
                                       echo '<input name="p" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button id="btn-titulo" class="btn btn-danger" type="button"><i class="glyphicon glyphicon-trash"></i></button>'; 
                                       echo '</span>';
                                   echo '</div>';
                               echo '</div>';
                               echo '<div id="250" class="input-group input-group-sm col-lg-10">';
                                   echo '<div class="input-group">';
                                       echo '<span class="input-group-addon" style="background-color:#80d4ff"><strong>Edición 250</strong></span>';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Mención de edición" class="btn btn-default btn-warning" type="button">$a</button>';
                                       echo '</span>';
                                       echo '<input name="edicion" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Resto de la mención de edición" class="btn btn-default btn-warning" type="button">$b</button>';
                                       echo '</span>';
                                       echo '<input name="b" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button id="btn-edicion" class="btn btn-danger" type="button"><i class="glyphicon glyphicon-trash"></i></button>'; 
                                       echo '</span>';
                                   echo '</div>';
                               echo '</div>';
                               echo '<div id="260" class="input-group input-group-sm col-lg-10">';
                                   echo '<div class="input-group">';
                                       echo '<span class="input-group-addon" style="background-color:#80d4ff"><strong>Editorial 260</strong></span>';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Lugar de publicación" class="btn btn-default btn-warning" type="button">$a</button>';
                                       echo '</span>';
                                       echo '<input name="ciudad" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Editorial" class="btn btn-default btn-warning" type="button">$b</button>';
                                       echo '</span>';
                                       echo '<input name="editorial" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Fecha" class="btn btn-basic" type="button">$c</button>';
                                       echo '</span>';
                                       echo '<input name="c" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Lugar de manufactura" class="btn btn-basic" type="button">$e</button>';
                                       echo '</span>';
                                       echo '<input name="e" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Manufacturador" class="btn btn-basic" type="button">$f</button>';
                                       echo '</span>';
                                       echo '<input name="f" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Fecha de manufactura" class="btn btn-basic" type="button">$g</button>';
                                       echo '</span>';
                                       echo '<input name="g" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button id="btn-editorial" class="btn btn-danger" type="button"><i class="glyphicon glyphicon-trash"></i></button>'; 
                                       echo '</span>';
                                   echo '</div>';
                               echo '</div>';
                               echo '<div id="300" class="input-group input-group-sm col-lg-10">';
                                   echo '<div class="input-group">';
                                       echo '<span class="input-group-addon" style="background-color:#80d4ff"><strong>Descripción 300</strong></span>';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Descripción" class="btn btn-basic" type="button">$a</button>';
                                       echo '</span>';
                                       echo '<input name="extensión" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Dimensiones" class="btn btn-basic" type="button">$c</button>';
                                       echo '</span>';
                                       echo '<input type="text" class="form-control">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Tipo de la unidad" class="btn btn-basic" type="button">$f</button>';
                                       echo '</span>';
                                       echo '<input type="text" class="form-control">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Tamaño de la unidad" class="btn btn-basic" type="button">$g</button>';
                                       echo '</span>';
                                       echo '<input type="text" class="form-control">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button id="btn-desc" class="btn btn-danger" type="button"><i class="glyphicon glyphicon-trash"></i></button>'; 
                                       echo '</span>';
                                   echo '</div>';
                               echo '</div>';
                               echo '<div id="440" class="input-group input-group-sm col-lg-10">';
                                   echo '<div class="input-group">';
                                       echo '<span class="input-group-addon" style="background-color:#80d4ff"><strong>Serie 440</strong></span>';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Tí-tulo" class="btn btn-default btn-warning" type="button">$a</button>';
                                       echo '</span>';
                                       echo '<input name="nombre_serie" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Volume nomber/sequential designation" class="btn btn-basic" type="button">$v</button>';
                                       echo '</span>';
                                       echo '<input name="v" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Nombre de parte/sección de la obra" class="btn btn-basic" type="button">$p</button>';
                                       echo '</span>';
                                       echo '<input name="p" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Nombre de parte/sección de la obra" class="btn btn-basic" type="button">$n</button>';
                                       echo '</span>';
                                       echo '<input name="n" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="ISSN" class="btn btn-basic" type="button">$x</button>';
                                       echo '</span>';
                                       echo '<input name="x" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button id="btn-serie" class="btn btn-danger" type="button"><i class="glyphicon glyphicon-trash"></i></button>'; 
                                       echo '</span>';
                                   echo '</div>';
                               echo '</div>';
                               echo '<div id="500" class="input-group input-group-sm col-lg-10">';
                                   echo '<div class="input-group">';
                                       echo '<span class="input-group-addon" style="background-color:#80d4ff"><strong>Nota general 500</strong></span>';
                                       echo '<span class="input-group-btn">';
                                           echo '<button class="btn btn-basic" type="button">$a</button>';
                                       echo '</span>';
                                       echo '<input type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button id="btn-ng" class="btn btn-danger" type="button"><i class="glyphicon glyphicon-trash"></i></button>'; 
                                       echo '</span>';
                                   echo '</div>';
                               echo '</div>';
                               echo '<div id="502" class="input-group input-group-sm col-lg-10">';
                                   echo '<div class="input-group">';
                                       echo '<span class="input-group-addon" style="background-color:#80d4ff"><strong>Nota de tesis 502</strong></span>';
                                       echo '<span class="input-group-btn">';
                                           echo '<button class="btn btn-basic" type="button">$a</button>';
                                       echo '</span>';
                                       echo '<input type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button id="btn-nt" class="btn btn-danger" type="button"><i class="glyphicon glyphicon-trash"></i></button>'; 
                                       echo '</span>';
                                   echo '</div>';
                               echo '</div>';
                               echo '<div id="504" class="input-group input-group-sm col-lg-10">';
                                   echo '<div class="input-group">';
                                       echo '<span class="input-group-addon" style="background-color:#80d4ff"><strong>Nota de bibliografía 504</strong></span>';
                                       echo '<span class="input-group-btn">';
                                           echo '<button class="btn btn-basic" type="button">$a</button>';
                                       echo '</span>';
                                       echo '<input name="nota_bi" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button id="btn-nb" class="btn btn-danger" type="button"><i class="glyphicon glyphicon-trash"></i></button>'; 
                                       echo '</span>';
                                   echo '</div>';
                               echo '</div>';
                               echo '<div id="505" class="input-group input-group-sm col-lg-10">';
                                   echo '<div class="input-group">';
                                       echo '<span class="input-group-addon" style="background-color:#80d4ff"><strong>Nota de contenido 505</strong></span>';
                                       echo '<span class="input-group-btn">';
                                           echo '<button class="btn btn-basic" type="button">$a</button>';
                                       echo '</span>';
                                       echo '<input name="notas" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Información variada" class="btn btn-basic" type="button">$g</button>';
                                       echo '</span>';
                                       echo '<input name="notas_g" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Mensión de responsabilidad" class="btn btn-basic" type="button">$r</button>';
                                       echo '</span>';
                                       echo '<input name="notas_r" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Tí-tulo" class="btn btn-basic" type="button">$t</button>';
                                       echo '</span>';
                                       echo '<input name="notas_t" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button id="btn-nc" class="btn btn-danger" type="button"><i class="glyphicon glyphicon-trash"></i></button>'; 
                                       echo '</span>';
                                   echo '</div>';
                               echo '</div>';
                               echo '<div id="520" class="input-group input-group-sm col-lg-10">';
                                   echo '<div class="input-group">';
                                       echo '<span class="input-group-addon" style="background-color:#80d4ff"><strong>Resumen 520</strong></span>';
                                       echo '<span class="input-group-btn">';
                                           echo '<button class="btn btn-basic" type="button">$a</button>';
                                       echo '</span>';
                                       echo '<input name="resumen" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button class="btn btn-basic" type="button">$b</button>';
                                       echo '</span>';
                                       echo '<input name="resumen_b" type="text" class="form-control">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button class="btn btn-basic" type="button">$c</button>';
                                       echo '</span>';
                                       echo '<input name="resumen_c" type="text" class="form-control">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button class="btn btn-basic" type="button">$u</button>';
                                       echo '</span>';
                                       echo '<input name="resumen_u" type="text" class="form-control">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button id="btn-resumen" class="btn btn-danger" type="button"><i class="glyphicon glyphicon-trash"></i></button>'; 
                                       echo '</span>';
                                   echo '</div>';
                               echo '</div>';
                               echo '<div id="650" class="input-group input-group-sm col-lg-10">';
                                   echo '<div class="input-group">';
                                       echo '<span class="input-group-addon" style="background-color:#80d4ff"><strong>Temas 650</strong></span>';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Epígrafe general" class="btn btn-default btn-warning" type="button">$a</button>';
                                       echo '</span>';
                                       echo '<input name="temas" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button class="btn btn-default btn-success" type="button">$2</button>';
                                       echo '</span>';
                                       echo '<input name="temas_2" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button id="btn-temas" class="btn btn-danger" type="button"><i class="glyphicon glyphicon-trash"></i></button>'; 
                                       echo '</span>';
                                   echo '</div>';
                               echo '</div>';
                               echo '<div id="700" class="input-group input-group-sm col-lg-10">';
                                   echo '<div class="input-group">';
                                       echo '<span class="input-group-addon" style="background-color:#80d4ff"><strong>Personal 700</strong></span>';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Nombre del autor" class="btn btn-warning" type="button">$a</button>';
                                       echo '</span>';
                                       echo '<input name="personal" type="text" class="form-control" value="">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Fechas" class="btn btn-basic" type="button">$d</button>';
                                       echo '</span>';
                                       echo '<input name="personal_d" type="text" class="form-control">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Relación" class="btn btn-warning" type="button">$e</button>';
                                       echo '</span>';
                                       echo '<input name="personal_e" type="text" class="form-control">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button data-toogle="tooltip" title="Pseudonimo" class="btn btn-success" type="button">$j</button>';
                                       echo '</span>';
                                       echo '<input name="personal_j" type="text" class="form-control">';
                                       echo '<span class="input-group-btn">';
                                           echo '<button id="btn-pers" class="btn btn-danger" type="button"><i class="glyphicon glyphicon-trash"></i></button>'; 
                                       echo '</span>';
                                   echo '</div>';
                               echo '</div>';
                           echo '</div>';
                       echo '</div>';
                       echo '<hr><hr>';
                       echo '<div class="form-horizontal">';
                           echo '<h3><b>Datos de portada</b></h3>';
                           echo '<div class="form-group">';
                               echo '<div class="input-group input-group-sm col-lg-10">';
                                   echo '<span class="input-group-addon">URL Documento:</span>';
                                   echo '<input name="url" class="form-control" value="">';
                               echo '</div>';
                               echo '<div class="input-group input-group-sm col-lg-10">';
                                   echo '<span class="input-group-addon">Thumb URL:</span>';
                                   echo '<input name="thumb" class="form-control" value="">';
                               echo '</div>';
                               echo '<div class="input-group input-group-sm col-lg-10">';
                                   echo '<span class="input-group-addon">Cover URL:</span>';
                                   echo '<input name="cover" class="form-control" value="">';
                               echo '</div>';
                           echo '</div>';
                       echo '</div>';
                       echo '<hr><hr>';
                       echo '<div class="form-horizontal">';
                           echo '<h3 class="card-header"><b>Copia</b></h3>';
                           echo '<div class="form-group">';
                               echo '<div class="input-group input-group-sm col-lg-10">';
                                   echo '<span class="input-group-addon"><strong>Cod. barras:</strong></span>';
                                   echo '<input name="num_inventario" type="text" class="form-control" value="">';
                                   echo '<span class="input-group-addon"><strong>No. Inv:</strong></span>';
                                   echo '<input name="inventory_num" type="text" class="form-control" value="">';
                                   echo '<span class="input-group-addon"><strong>Copia:</strong></span>';
                                   echo '<input name="copia" type="text" class="form-control" value="">';
                               echo '</div>';
                               echo '<div class="input-group input-group-sm col-lg-10">';
                                   echo '<span class="input-group-addon"><strong>Ubicación:</strong></span>';
                                   echo '<input name="ubicacion" type="text" class="form-control" value="">';
                                   echo '<span class="input-group-addon"><strong>Prefijo:</strong></span>';
                                   echo '<input name="prefijo" type="text" class="form-control">';
                                   echo '<span class="input-group-addon"><strong>Clasificación:</strong></span>';
                                   echo '<input name="clasificacion" type="text" class="form-control" value="">';
                               echo '</div>';
                               echo '<div class="input-group input-group-sm col-lg-10">';
                                   echo '<span class="input-group-addon"><strong>Biblioteca:</strong></span>';
                                   echo '<input name="biblioteca" type="text" class="form-control" value="">';
                                   echo '<span class="input-group-addon"><strong>Vol. / No.:</strong></span>';
                                   echo '<input name="volno" type="text" class="form-control" value="">';
                               echo '</div>';
                               echo '<div class="input-group input-group-sm col-lg-10">';
                                   echo '<span class="input-group-addon"><strong>Circulación:</strong></span>';
                                   echo '<input name="tipo_circ" type="text" class="form-control" value="">';
                                   echo '<span class="input-group-addon"><strong>Status:</strong></span>';
                                   echo '<input name="status" type="text" class="form-control" value="">';
                                   echo '<span class="input-group-addon"><strong>Fecha entrada:</strong></span>';
                                   echo '<input name="fecha_entrada" type="text" class="form-control" value="">';
                               echo '</div>';
                               echo '<div class="input-group input-group-sm col-lg-10">';
                                   echo '<span class="input-group-addon"><strong>Procedencia:</strong></span>';
                                   echo '<input name="proce" type="text" class="form-control" value="">';
                                   echo '<span class="input-group-addon"><strong>Tipo:</strong></span>';
                                   echo '<input name="type" type="text" class="form-control" value="">';
                               echo '</div>';
                               echo '<div class="input-group input-group-sm col-lg-10">';
                                   echo '<span class="input-group-addon"><strong>Factura:</strong></span>';
                                   echo '<input name="fact" type="text" class="form-control" value="">';
                                   echo '<span class="input-group-addon"><strong>Precio:</strong></span>';
                                   echo '<input name="precio" type="text" class="form-control" value="">';
                               echo '</div>';
                               echo '<div class="input-group input-group-sm col-lg-10">';
                                   echo '<span class="input-group-addon"><strong>Hiperlink:</strong></span>';
                                   echo '<input name="hyperlink" type="text" class="form-control" value="">';
                               echo '</div>';
                               echo '<div class="input-group input-group-sm col-lg-10">';
                                   echo '<span class="input-group-addon"><strong>Notas:</strong></span>';
                                   echo '<input name="notas" type="text" class="form-control" value="">';
                               echo '</div>';
                           echo '</div>';
                       echo '</div>'; 
        }
    }
}
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

